---
title: 'Objectives and Project Description'
subtitle: 'Summer 2022 Internship '
output: 
  bookdown::pdf_document2:
    toc: false
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Objectives

The objective for the summer is to provide data science training and mentorship for the student to prepare them for industry or academia related to social justice initiatives. By the end of summer, the student will be able to do the following:

1. Able to apply appropriate data wrangling and visualization tools on the given data set.
2. Able to apply appropriate data exploratory analysis, statistical models, and data science algorithms.
3. Able to integrate relevant domain knowledge for aiding the analysis and communicate results effectively.

## Outcomes

Throughout the summer project, the student will undertake advanced training in R and R Studio and as well as mentorship in advanced statistical methods. Below are the items that the student will deliver by the end of summer:

1. A final report of the methods, data explorations, visualizations, results and analysis of the project.
2. A $48'' \times 36''$ research poster, which is to be presented at the Reed College undergraduate research poster session in Fall 2022.

## Project

### Title

Examining Racial Disparities in Law Enforcement Use of Force

### Description

This project examines nationwide data on use of deadly force by police to investigate the presence and extent of racial bias in the U.S. Our work utilizes the [National Police Shooting Database](https://github.com/washingtonpost/data-police-shootings){target="_blank"}, compiled by the Washington Post. We supplement this data set by utilizing the [Mapping Violence database](https://mappingpoliceviolence.org/){target="_blank"} of Campaign Zero and the [National Officer-Involved Homicide Database](https://fatalencounters.org/){target="_blank"} of the University of Southern California. Using modern data science methods, the student intern - under my supervision and mentorship - will investigate implicit racial prejudice in police-involved civilian deaths and examine the associations between race/ethnicity and established measures of threat perceptions. 

The pervasive presence of systemic racism in policing in the United States poses grievous threats to the life and well-being of racial minorities. Examining racial disparities in law enforcement use of force has broader implications in the structures and policies of our academic institutions, financial institutions, criminal justice system, and health care system.
